# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Imagine
tagline:          The Perks
url:              http://imaginetheperks.com
paginate:         1
baseurl:          /
author:
  name:           Kurt Wagner
  url:            https://twitter.com/kurtwagnerau
  email:          kurt.wagner@prowla.com

# Custom vars
version:          0.0.1
github:
  repo:           https://github.com/kurtwagner/Imaginetheperks
